experimentName: Muesli_minigrid
searchSpace:
  iteration:
    _type: choice
    _value: [20, 80, 160]
  replay_proportion:
    _type: choice
    _value: [75, 95]
  start_lr:
    _type: choice
    _value: [0.0003, 0.0002]
  expriment_length:
    _type: choice
    _value: [4000]    
  policy_loss_weight:
    _type: choice
    _value: [1, 3]    
  resize_height:
    _type: choice
    _value: [40, 80]
  resize_width:
    _type: choice
    _value: [60, 120]
    


experimentWorkingDirectory: ./nni-experiments
trialCommand: python Muesli_lunar_rgb.py
trialGpuNumber: 1
trialConcurrency: 10
maxTrialNumber: 100
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 100