experimentName: Muesli_lunar_rgb
searchSpace:

  mb_dim:
    _type: choice
    _value: [128]
  iteration:
    _type: choice
    _value: [20]

  use_fixed_random_seed:
    _type: choice
    _value: [True] #,False]
  random_seed:
    _type: choice
    _value: [4,5,6,7]


experimentWorkingDirectory: ./nni-experiments
trialCommand: python Muesli_lunar_rgb.py
trialGpuNumber: 1
trialConcurrency: 8
maxTrialNumber: 100
tuner:
  name: Random
trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 400