experimentName: Muesli
searchSpace:
  regularizer_multiplier:
    _type: choice
    _value: [1]
  mb_dim:
    _type: choice
    _value: [128, 256, 512]
  iteration:
    _type: choice
    _value: [20, 80]
  mlp_width:
    _type: choice
    _value: [128, 256]
trialCommand: python Muesli_LunarLander.py
trialGpuNumber: 1
trialConcurrency: 10
maxTrialNumber: 100
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 20