experimentName: Muesli_minigrid
searchSpace:
  regularizer_multiplier:
    _type: choice
    _value: [1, 3, 10]
  alpha_target:
    _type: choice
    _value: [0.01, 0.1]
  mb_dim:
    _type: choice
    _value: [32, 128]
  iteration:
    _type: choice
    _value: [20, 80]
  replay_proportion:
    _type: choice
    _value: [75]
  start_lr:
    _type: choice
    _value: [0.0003]
  expriment_length:
    _type: choice
    _value: [4000]    
  policy_loss_weight:
    _type: choice
    _value: [1, 3]    
  resize_height:
    _type: choice
    _value: [72]
  resize_width:
    _type: choice
    _value: [96]
  stack_action_plane:
    _type: choice
    _value: [False]
    


experimentWorkingDirectory: ./nni-experiments
trialCommand: python Muesli_lunar_rgb.py
trialGpuNumber: 1
trialConcurrency: 10
maxTrialNumber: 100
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 100