experimentName: Muesli_lunar_rgb
searchSpace:

  random_seed:
    _type: choice
    _value: [42,52,62,72,82,92,93,94,95,96,97,98]   
  use_proj:
    _type: choice
    _value: [True]   
  second_term_weight:
    _type: choice
    _value: [1]    
  mixed_prior:
    _type: choice
    _value: [True]
  stacking_frame:
    _type: choice
    _value: [4]
  mb_dim:
    _type: choice
    _value: [128]
  iteration:
    _type: choice
    _value: [20]
  alpha_target:
    _type: choice
    _value: [0.01]

experimentWorkingDirectory: ./nni-experiments
trialCommand: python Muesli_lunar_rgb.py
trialGpuNumber: 1
trialConcurrency: 8
maxTrialNumber: 100
tuner:
  name: Random
trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 400